name: "Get the merged pull request information"
description: "Get information about the pull request merged into the default branch"
author: "yu-iskw"

branding:
  icon: "code"
  color: "blue"

inputs:
  github-token:
    description: "GitHub token"
    required: true

outputs:
  pull-request-number:
    description: "The pull request number of the pull request created by the composite GitHub Action"
    value: ${{ steps.get_pr_info.outputs.pull_request_number }}
  pull-request-creator:
    description: "The GitHub account name who created the pull request"
    value: ${{ steps.get_pr_info.outputs.pull_request_creator }}
  pull-request-title:
    description: "The title of the pull request"
    value: ${{ steps.get_pr_info.outputs.pull_request_title }}
  pull-request-branch:
    description: "The branch of the pull request"
    value: ${{ steps.get_pr_info.outputs.pull_request_branch }}

runs:
  using: "composite"
  steps:
    - name: "Checkout the repository"
      uses: actions/checkout@v3

    - name: "Get commit hash of the merged pull request"
      id: get_commit_hash
      shell: bash
      run: |
        echo "commit_hash=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

    - name: "Fetch merged pull request information"
      id: get_pr_info
      uses: actions/github-script@v6
      with:
        github-token: ${{ inputs.github-token }}
        debug: true
        script: |
          const commitHash = "${{ steps.get_commit_hash.outputs.commit_hash }}";
          const owner = context.repo.owner;
          const repo = context.repo.repo;

          console.log(`Fetching pull request for commit hash: ${commitHash}`);

          // Step 1: Search for the merged pull request by commit hash
          const { data: { items } } = await github.rest.search.issuesAndPullRequests({
            q: `${commitHash} repo:${owner}/${repo} type:pr is:merged`,
          });

          if (items.length === 0) {
            console.log(`No merged pull request found for commit hash: ${commitHash}`);
            throw new Error("No merged pull request found.");
          }

          const prNumber = items[0].number;
          console.log(`Pull request number found: ${prNumber}`);

          // Step 2: Get detailed pull request information
          const { data: pr } = await github.rest.pulls.get({
            owner,
            repo,
            pull_number: prNumber,
          });

          const prCreator = pr.user.login;
          const prTitle = pr.title;
          const prBranch = pr.head.ref;

          console.log(`Pull request details:`);
          console.log(`- Number: ${prNumber}`);
          console.log(`- Creator: ${prCreator}`);
          console.log(`- Title: ${prTitle}`);
          console.log(`- Branch: ${prBranch}`);

          // Set outputs
          return {
            pull_request_number: prNumber,
            pull_request_creator: prCreator,
            pull_request_title: prTitle,
            pull_request_branch: prBranch,
          };
