name: "Get the merged pull request information"
description: "Get information about the pull request merged into the default branch"
author: "yu-iskw"

branding:
  icon: "code"
  color: "blue"

inputs:
  github-token:
    description: "GitHub token"
    required: true

outputs:
  pull-request-number:
    description: "The pull request number of the pull request created by the composite GitHub Action"
    value: ${{ steps.get_pr_info.outputs.pull_request_number }}
  pull-request-creator:
    description: "The GitHub account name who created the pull request"
    value: ${{ steps.get_pr_info.outputs.pull_request_creator }}
  pull-request-title:
    description: "The title of the pull request"
    value: ${{ steps.get_pr_info.outputs.pull_request_title }}
  pull-request-branch:
    description: "The branch of the pull request"
    value: ${{ steps.get_pr_info.outputs.pull_request_branch }}

runs:
  using: "composite"
  steps:
    - name: "Checkout the repository"
      uses: actions/checkout@v3

    - name: "Get commit hash of the merged pull request"
      id: get_commit_hash
      shell: bash
      run: |
        echo "commit_hash=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

    - name: "Fetch merged pull request information"
      id: get_pr_info
      uses: actions/github-script@v6
      with:
        github-token: ${{ inputs.github-token }}
        debug: true
        script: |
          const commitHash = "${{ steps.get_commit_hash.outputs.commit_hash }}";
          const owner = context.repo.owner;
          const repo = context.repo.repo;

          console.log(`Fetching pull request for commit hash: ${commitHash}`);

          // Use the dedicated endpoint to list pull requests associated with the commit
          const { data: pulls } = await github.rest.repos.listPullRequestsAssociatedWithCommit({
            owner,
            repo,
            commit_sha: commitHash,
            mediaType: {
              previews: ['groot']
            }
          });

          if (pulls.length === 0) {
            console.log(`No pull requests associated with commit hash: ${commitHash}`);
            throw new Error("No merged pull request found.");
          }

          const pr = pulls[0]; // Use the first associated PR
          console.log(`Pull request details:`);
          console.log(`- Number: ${pr.number}`);
          console.log(`- Creator: ${pr.user.login}`);
          console.log(`- Title: ${pr.title}`);
          console.log(`- Branch: ${pr.head.ref}`);

          return {
            pull_request_number: pr.number,
            pull_request_creator: pr.user.login,
            pull_request_title: pr.title,
            pull_request_branch: pr.head.ref,
          };

