# The YAML contains definitions of inputs of the composite GitHub Action.
name: "Get the merged pull request information"
description: "Get information about the pull request merged into the default branch"
author: "yu-iskw"

branding:
  icon: "code"
  color: "blue"

inputs:
  github-token:
    description: "GitHub token"
    required: true

outputs:
  pull-request-number:
    description: "The pull request number of the pull request created by the composite GitHub Action"
    value: ${{ steps.get_pr_number.outputs.result }}
  pull-request-creator:
    description: "The GitHub account name who created the pull request"
    value: ${{ steps.get_pr_creator.outputs.result }}
  pull-request-title:
    description: "The title of the pull request"
    value: ${{ steps.get_pr_title.outputs.result }}
  pull-request-branch:
    description: "The branch of the pull request"
    value: ${{ steps.get_pr_branch.outputs.result }}

runs:
  using: "composite"
  steps:
    # We have to chec kout the default branch outside the composite GitHub Action.
    - name: "Checkout"
      uses: actions/checkout@v3
    - name: "Get the commit hash of the merged pull request"
      id: get_commit_hash
      shell: bash
      run: |
        echo "commit_hash=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
    # Get the pull request number from the commit hash using github-script

    # Get the GitHub account name who created the merged pull request by the pull request number
    - name: "Get the GitHub account name who created the merged pull request"
      id: get_pr_creator
      uses: actions/github-script@v6
      with:
        github-token: ${{ inputs.github-token }}
        debug: true
        result-encoding: string
        script: |
          const pr_number = "${{ steps.get_pr_number.outputs.result }}";
          const pr = await github.rest.pulls.get({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: pr_number
          });
          const pr_creator = pr.data.user.login;
          console.log(`The GitHub account name who created the merged pull request is ${pr_creator}`);
          return pr_creator;

    - name: "Get the pull request title"
      id: get_pr_title
      uses: actions/github-script@v6
      with:
        github-token: ${{ inputs.github-token }}
        debug: true
        result-encoding: string
        script: |
          const pr_number = "${{ steps.get_pr_number.outputs.result }}";
          const pr = await github.rest.pulls.get({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: pr_number
          });
          const pr_title = pr.data.title;
          console.log(`The title of the merged pull request is ${pr_title}`);
          return pr_title;
    - name: "Get the pull request branch"
      id: get_pr_branch
      uses: actions/github-script@v6
      with:
        github-token: ${{ inputs.github-token }}
        debug: true
        result-encoding: string
        script: |
          const pr_number = "${{ steps.get_pr_number.outputs.result }}";
          const pr = await github.rest.pulls.get({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: pr_number
          });
          const pr_branch = pr.data.head.ref; 
          return pr_branch; 
